### ISSUE TITLE
ubuntu ppa does not work

### ISSUE THREAD

**Issue by xavierle** [localwiki/localwiki#711]
i tried to deploy ubuntu as on this docs

http://localwiki.readthedocs.org/en/latest/install.html

i have the following errors : 

78718f6c8af3ee617f715cd99395b1941ea7a68e refs/tags/0.3.3
  Could not find a tag or branch 'b4991c140849901d2f8842df2c4672813e73381b', assuming commit.
  Running command /usr/bin/git rev-parse HEAD
  476d1bc11c1757b0b3dedd9a0e4a9723dad8425f
  Running command /usr/bin/git checkout -q b4991c140849901d2f8842df2c4672813e73381b
  Complete output from command /usr/bin/git checkout -q b4991c140849901d2f8842df2c4672813e73381b:

----------------------------------------
Cleaning up...
  Removing temporary dir /usr/share/localwiki/env/build...
Command /usr/bin/git checkout -q b4991c140849901d2f8842df2c4672813e73381b failed with error code 128 in /usr/share/localwiki/env/src/django-honeypot
Exception information:
Traceback (most recent call last):
  File "/usr/share/localwiki/env/lib/python2.6/site-packages/pip-1.5.6-py2.6.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/share/localwiki/env/lib/python2.6/site-packages/pip-1.5.6-py2.6.egg/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/share/localwiki/env/lib/python2.6/site-packages/pip-1.5.6-py2.6.egg/pip/req.py", line 1140, in prepare_files
    req_to_install.update_editable(not self.is_download)
  File "/usr/share/localwiki/env/lib/python2.6/site-packages/pip-1.5.6-py2.6.egg/pip/req.py", line 483, in update_editable
    vcs_backend.obtain(self.source_dir)
  File "/usr/share/localwiki/env/lib/python2.6/site-packages/pip-1.5.6-py2.6.egg/pip/vcs/git.py", line 118, in obtain
    call_subprocess([self.cmd, 'checkout', '-q'] + rev_options, cwd=dest)
  File "/usr/share/localwiki/env/lib/python2.6/site-packages/pip-1.5.6-py2.6.egg/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /usr/bin/git checkout -q b4991c140849901d2f8842df2c4672813e73381b failed with error code 128 in /usr/share/localwiki/env/src/django-hone$

**Comment by xavierle** [comment]
it seems the projects is more about service delivery
